import { Link } from 'react-router-dom';
import { FiArrowRight, FiArrowUpRight, FiCheck, FiCode, FiCpu, FiCloud, FiGlobe, FiLayers, FiSmartphone } from 'react-icons/fi';
import MarketingSEO from '../components/common/MarketingSEO';
import { services, capabilities, consultingFaqs } from '../data/consulting';

const icons = { web: FiGlobe, app: FiSmartphone, ai: FiCpu, layers: FiLayers, code: FiCode, cloud: FiCloud };
const primary = 'inline-flex items-center justify-center gap-3 rounded-xl bg-gradient-to-r from-green-500 to-blue-600 px-6 py-3.5 font-semibold text-white hover:brightness-110 transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-green-400';
const label = 'text-xs font-semibold uppercase tracking-[0.2em] text-green-400';

export default function Consulting() {
  return <div className="bg-gray-950 text-gray-300 overflow-hidden">
    <MarketingSEO page="consulting" />
    <section className="relative bg-gradient-to-br from-slate-800 via-gray-900 to-gray-950 pt-32 pb-16 sm:pt-40 sm:pb-24">
      <div aria-hidden="true" className="absolute right-0 top-20 h-96 w-96 rounded-full bg-blue-500/10 blur-3xl pointer-events-none" />
      <div className="relative max-w-[1200px] mx-auto px-6 lg:px-8">
        <nav aria-label="Breadcrumb" className="flex gap-3 text-sm text-gray-400 mb-12"><Link to="/" className="hover:text-white">Home</Link><span aria-hidden="true">/</span><span aria-current="page" className="text-gray-200">IT Consulting</span></nav>
        <div className="grid lg:grid-cols-[1.2fr_1fr] items-center gap-12 lg:gap-16">
          <div>
            <p className={label}>Miraista · Consulting & engineering</p>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white leading-[1.1] mt-5">IT consulting.<br />Product engineering.<br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-400">Built around you.</span></h1>
            <p className="text-lg text-gray-400 leading-relaxed mt-7 max-w-xl">From your next website to a complete AI-powered platform. We help you choose the right technology, build your product, and bring it to production.</p>
            <div className="flex flex-wrap gap-4 mt-8"><Link to="/contacts" className={primary}>Discuss Your Project <FiArrowUpRight aria-hidden="true" /></Link><a href="#capabilities" className="inline-flex items-center gap-2 px-3 py-3.5 text-gray-200 hover:text-green-300">Explore our stack <FiArrowRight aria-hidden="true" /></a></div>
            <p className="text-xs text-gray-500 mt-6">Web & mobile · AI & automation · Cloud · White-label solutions</p>
          </div>
          <div className="relative rounded-3xl border border-gray-700 bg-gray-900/80 p-6 sm:p-8 shadow-2xl">
            <div className="flex items-center justify-between pb-5 border-b border-gray-800"><span className="text-xs uppercase tracking-[0.2em] text-gray-400">From idea to infrastructure</span><span aria-hidden="true" className="flex gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-green-400" /><span className="w-1.5 h-1.5 rounded-full bg-blue-400" /></span></div>
            <div className="rounded-xl border border-green-500/30 bg-gradient-to-r from-green-500/10 to-blue-500/10 p-5 mt-6"><p className="text-xs text-green-300 uppercase tracking-widest">Start with the problem</p><p className="text-2xl font-semibold text-white mt-2">Your vision. Our engineering.</p></div>
            <div aria-hidden="true" className="h-6 w-px bg-gradient-to-b from-green-400/60 to-gray-700 mx-auto" />
            <div className="grid grid-cols-2 gap-3">{[[FiGlobe, 'Experiences', 'Web & mobile'], [FiCpu, 'Intelligence', 'AI & automation'], [FiLayers, 'Foundation', 'APIs & data'], [FiCloud, 'Infrastructure', 'Cloud & DevOps']].map(([Icon, title, caption]) => <div key={title} className="rounded-xl border border-gray-700/70 bg-gray-800/40 p-4"><Icon aria-hidden="true" className="text-blue-400 w-5 h-5 mb-3" /><p className="text-white font-medium">{title}</p><p className="text-xs text-gray-400 mt-1">{caption}</p></div>)}</div>
            <p className="flex items-center justify-center gap-2 text-sm text-gray-400 mt-6"><FiCheck aria-hidden="true" className="text-green-400" />One partner, from architecture to launch</p>
          </div>
        </div>
      </div>
    </section>

    <section aria-labelledby="services-title" className="max-w-[1200px] mx-auto px-6 lg:px-8 py-20 sm:py-24">
      <p className={label}>What we can build together</p><h2 id="services-title" className="text-3xl sm:text-4xl font-bold text-white mt-4">Engineering for your next step.</h2><p className="max-w-2xl mt-4 text-gray-400 leading-relaxed">A new product, an existing platform, or a workflow that needs a better way. Start with the support your business needs.</p>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-10">{services.map((service) => { const Icon = icons[service.icon]; return <article key={service.title} className="rounded-2xl border border-gray-800 bg-gray-900/50 p-7 hover:border-blue-500/40 transition-colors"><div className="inline-flex rounded-xl bg-gradient-to-br from-green-500/10 to-blue-500/10 p-3 mb-6"><Icon aria-hidden="true" className="h-6 w-6 text-green-400" /></div><h3 className="text-xl text-white font-semibold">{service.title}</h3><p className="mt-3 leading-relaxed text-gray-400">{service.description}</p><p className="mt-6 pt-4 border-t border-gray-800 text-xs leading-relaxed text-blue-300">{service.detail}</p></article>; })}</div>
    </section>

    <section id="capabilities" aria-labelledby="capabilities-title" className="scroll-mt-28 bg-gray-900/40 border-y border-gray-800 py-20 sm:py-24">
      <div className="max-w-[1200px] mx-auto px-6 lg:px-8">
        <div className="grid lg:grid-cols-2 gap-6 items-end mb-10"><div><p className={label}>Technology capability overview</p><h2 id="capabilities-title" className="text-3xl sm:text-4xl font-bold text-white mt-4">The right tools.<br />For your particular problem.</h2></div><p className="text-gray-400 leading-relaxed lg:max-w-md lg:justify-self-end">We choose the stack around your product, existing systems, and operating needs. Explore our capabilities across the full development lifecycle.</p></div>
        <div className="space-y-4">{capabilities.map(capability => <article key={capability.number} className="rounded-2xl border border-gray-800 bg-gray-950/70 p-6 sm:p-8">
          <div className="grid lg:grid-cols-[1fr_1fr] gap-6"><div className="flex gap-5"><span className="text-green-400 font-mono text-sm pt-1">{capability.number}</span><div><h3 className="text-xl sm:text-2xl font-semibold text-white">{capability.title}</h3><p className="mt-2 text-sm leading-relaxed text-gray-400 max-w-md">{capability.description}</p></div></div><ul aria-label={`${capability.title} highlights`} className="flex flex-wrap items-center gap-2 list-none">{capability.featured.map(tech => <li key={tech} className="rounded-lg border border-gray-700 bg-gray-800/60 px-3 py-2 text-sm text-gray-200">{tech}</li>)}</ul></div>
          <details className="mt-6 border-t border-gray-800 pt-4 group"><summary className="cursor-pointer text-sm text-blue-300 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-green-400">Explore all {capability.title.toLowerCase()} technologies</summary><dl className="mt-6 grid md:grid-cols-2 gap-6">{capability.groups.map(([name, value]) => <div key={name}><dt className="text-sm text-white font-medium">{name}</dt><dd className="text-sm text-gray-400 leading-7 mt-2">{value}</dd></div>)}</dl></details>
        </article>)}</div>
        <div className="mt-6 rounded-2xl border border-blue-500/20 bg-gradient-to-r from-green-500/5 to-blue-500/10 p-6 sm:p-8"><p className={label}>AI grounded in your data</p><h3 className="text-xl text-white font-semibold mt-3">A connected RAG pipeline</h3><ol className="mt-6 grid sm:grid-cols-5 gap-3 list-none">{['Ingest & chunk', 'Embed', 'Store vectors', 'Retrieve & rerank', 'Generate with an LLM'].map((step, i) => <li key={step} className="rounded-xl bg-gray-950/60 border border-gray-700/60 p-4"><span className="text-xs font-mono text-green-400">0{i + 1}</span><p className="mt-2 text-sm text-gray-200">{step}</p></li>)}</ol><p className="mt-5 text-sm text-gray-400 leading-relaxed">Document parsing, retrieval, and evaluation work together to connect model responses to relevant business information.</p></div>
      </div>
    </section>

    <section aria-labelledby="architecture-title" className="max-w-[1200px] mx-auto px-6 lg:px-8 py-20 sm:py-24">
      <p className={label}>Designed to work together</p><h2 id="architecture-title" className="text-3xl sm:text-4xl font-bold text-white mt-4">Beyond a list of technologies.</h2>
      <div className="grid lg:grid-cols-2 gap-6 mt-10"><div className="rounded-2xl border border-gray-800 p-7"><h3 className="text-xl text-white font-semibold mb-5">Full-stack combinations</h3><dl className="space-y-4">{[['MERN / MEAN', 'MongoDB + Express + React or Angular + Node.js'], ['T3 stack', 'Next.js + tRPC + Tailwind CSS + Prisma'], ['JAMstack', 'Next.js or Astro + a headless CMS'], ['Python-powered products', 'Django + PostgreSQL + React, or FastAPI + Next.js + Supabase'], ['AI SaaS', 'Next.js + FastAPI + LangChain + Pinecone']].map(([name, stack]) => <div key={name} className="border-b border-gray-800 pb-4 last:border-0 last:pb-0"><dt className="text-sm text-green-300">{name}</dt><dd className="mt-1 text-sm text-gray-400 leading-relaxed">{stack}</dd></div>)}</dl></div>
      <div className="space-y-5"><div className="rounded-2xl border border-gray-800 bg-gray-900/50 p-7"><h3 className="text-xl text-white font-semibold mb-3">Architecture patterns</h3><p className="text-gray-400 text-sm leading-7">Microservices, event-driven architecture, serverless, edge computing, domain-driven design, API gateways / BFF, multi-tenant SaaS, and monorepos with Turborepo or Nx.</p></div><div className="rounded-2xl border border-gray-800 bg-gray-900/50 p-7"><h3 className="text-xl text-white font-semibold mb-3">Quality, security & operations</h3><p className="text-gray-400 text-sm leading-7">End-to-end testing with Playwright, Cypress, or Selenium. Performance checks with k6, JMeter, and Lighthouse. Code and security tooling including SonarQube, OWASP ZAP, Snyk, Vault, and AWS IAM / KMS.</p><p className="text-gray-400 text-sm leading-7 mt-3">API gateway and service mesh options include Kong, Nginx, Istio, Traefik, AWS API Gateway, and Envoy. Compliance tooling can support your SOC 2 or ISO 27001 readiness work.</p></div></div></div>
    </section>

    <section aria-labelledby="products-title" className="bg-gray-900/40 border-y border-gray-800 py-20">
      <div className="max-w-[1200px] mx-auto px-6 lg:px-8"><p className={label}>Our own products</p><h2 id="products-title" className="text-3xl sm:text-4xl font-bold text-white mt-4">Explore what we build.</h2><p className="mt-4 text-gray-400">Our product portfolio spans digital lending, conversational AI, and vehicle assessment.</p><div className="grid md:grid-cols-3 gap-5 mt-9">{[['LendOS', 'Digital lending infrastructure for banks, NBFCs, and fintechs.', '/lendos'], ['AI Chatbot', 'Conversational assistants for customer questions and business knowledge.', '/chatbotpage'], ['Vehicle Damage Assessment', 'AI-powered vehicle image analysis and damage assessment.', '/claimupload']].map(([name, description, path]) => <Link key={path} to={path} className="group rounded-2xl border border-gray-700/60 p-7 hover:border-green-400/50 transition-colors"><h3 className="text-xl text-white font-semibold">{name}</h3><p className="text-gray-400 text-sm leading-relaxed mt-3">{description}</p><span className="inline-flex items-center gap-2 text-green-300 text-sm mt-6">Explore product <FiArrowUpRight aria-hidden="true" /></span></Link>)}</div></div>
    </section>

    <section aria-labelledby="process-title" className="max-w-[1200px] mx-auto px-6 lg:px-8 py-20 sm:py-24"><p className={label}>How we work</p><h2 id="process-title" className="text-3xl sm:text-4xl font-bold text-white mt-4">A clear path from idea to launch.</h2><ol className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8 mt-12 list-none">{[['Discover', 'Understand your goals, users, constraints, and current systems.'], ['Design', 'Define the architecture, scope, and technology choices together.'], ['Build', 'Develop, integrate, test, and iterate with your feedback.'], ['Launch & evolve', 'Deploy, monitor, and plan ongoing support and improvements.']].map(([title, description], i) => <li key={title} className="border-t border-gray-700 pt-5"><span className="text-green-400 text-sm font-mono">0{i + 1}</span><h3 className="text-lg text-white font-semibold mt-4">{title}</h3><p className="text-gray-400 text-sm leading-relaxed mt-3">{description}</p></li>)}</ol></section>

    <section aria-labelledby="faq-title" className="max-w-3xl mx-auto px-6 pb-20"><p className={label}>Before we get started</p><h2 id="faq-title" className="text-3xl font-bold text-white mt-4 mb-8">Your questions, answered.</h2><div className="space-y-3">{consultingFaqs.map(([question, answer]) => <details key={question} className="rounded-xl border border-gray-800 bg-gray-900/50 p-5"><summary className="text-gray-200 font-medium cursor-pointer focus-visible:outline focus-visible:outline-2 focus-visible:outline-green-400">{question}</summary><p className="text-gray-400 leading-relaxed text-sm mt-4">{answer}</p></details>)}</div></section>

    <section aria-labelledby="contact-title" className="max-w-[1200px] mx-auto px-6 lg:px-8 pb-20"><div className="rounded-3xl border border-green-500/20 bg-gradient-to-br from-green-500/10 via-gray-900 to-blue-500/10 p-8 sm:p-14 text-center"><p className={label}>Let’s build what’s next</p><h2 id="contact-title" className="text-3xl sm:text-5xl font-bold text-white mt-4">Have a project in mind?</h2><p className="text-gray-400 max-w-xl mx-auto mt-5 leading-relaxed">Tell us what you want to build, improve, or automate. We’ll help you work out the next step.</p><div className="flex flex-col sm:flex-row justify-center items-center gap-5 mt-8"><Link to="/contacts" className={primary}>Discuss Your Project <FiArrowUpRight aria-hidden="true" /></Link><a href="mailto:ceo@miraista.com" className="text-gray-200 hover:text-green-300">ceo@miraista.com</a></div></div></section>
  </div>;
}
